<template>
  <div class="gallery">
    <header class="gallery-header">
      <span class="draw-icon"></span>
      <h2 class="gallery-text">Gallery</h2>
      <span class="window-icons"
        ><i class="fas fa-window-minimize"></i
        ><i class="far fa-window-maximize"></i><i class="fas fa-times"></i
      ></span>
    </header>

    <aside class="gallery-wrapper">
      <ul class="gallery-list">
        <li class="gallery-item vibrate" id="gallery"></li>
      </ul>
    </aside>
  </div>
</template>

<script>
import firebase from "../../firebase";

export default {
  name: "Gallery",
  mounted() {
    // Create a root reference
    const storageRef = firebase.storage().ref();
    const node = document.createElement("LI");

    /* list all returns a list of all images*/
    const allImages = storageRef.listAll();
    /*grab all the images' download URLS from firebase storage and then call displayImage*/
    allImages.then(function(result) {
      result.items.forEach(function(imageRef) {
        imageRef.getDownloadURL().then((result) => {
          const retrievedImage = result;
          const img = new Image(130, 130);
          img.src = retrievedImage;
          /*append image to dynamic li*/
          node.appendChild(img);
          /*append that li to the dom*/
          document.getElementById("gallery").appendChild(node);
        });
      });
    });
  },
};
</script>

<style>
.gallery{
  border: 1px solid
}

.gallery-header{
  border-bottom: 1px solid black;
  display: flex;
  justify-content: space-between;
  background: #82B3FF;
  margin-bottom: 1rem;
}

.window-icons {
  padding: 10px;
  color: white;
  -webkit-text-stroke: .8px black;
}

.draw-icon {
  padding: 10px;
  color: white;
}

.fas {
  padding: 5px;
}

.gallery-wrapper {
  margin: 10px;
  max-height: 800px;
  max-width: 700px;
  grid-area: gallery;
  overflow-y: scroll;
  overflow-x: hidden;
}

.gallery-wrapper li {
  display: grid;
  grid-template-columns: repeat(4, min-content);
  grid-template-rows: auto;
}

img {
  margin: 5px;
  background: white;
  border-radius: 25px;
}

span {
  color: #f0df45;
  -webkit-text-stroke: 0.5px #222222;
}

.vibrate {
  -webkit-animation: vibrate-3 3s linear infinite alternate both;
  animation: vibrate-3 3s linear infinite alternate both;
}

.gallery-text {
  padding-top: 10px;
  text-align: left;
  text-transform: uppercase;
  -webkit-text-stroke: 1px #3D3B30;
  font-size: 1.6rem;
  color: white;
  letter-spacing: 1px;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-2-24 9:39:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation vibrate-3
 * ----------------------------------------
 */
@-webkit-keyframes vibrate {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}

@-webkit-keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}

@keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
    transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
    transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
    transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
    transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
    transform: translate(0);
  }
}
</style>
